version: '2'
services:
  checkupd:
    image: checkupd:v1.0.0
    container_name: checkupd
    restart: always
    ports:
      - "9009:9009"
    network_mode: "host"
    volumes:
      - "./checkup_config/checkup.json:/checkup/checkup.json"
      - "./checkup_config/logs:/checkup/logs"
  statuspage:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "./checkup_config/logs:/statuspage/logs"
    - "./statuspage:/statuspage"
    - "./caddy_config/Caddyfile:/etc/Caddyfile"
    - "./caddy_config/caddy-logs:/root/.caddy/logs"
    - "./caddy_config/caddy-errors:/root/.caddy/errors"
