version: '2'
services:
  statuspage:
    image: abiosoft/caddy
    container_name: caddy
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "./statuspage:/statuspage"
    - "./caddy_config/Caddyfile:/etc/Caddyfile"
    - "./caddy_config/caddy-logs:/root/.caddy/logs"
    - "./caddy_config/caddy-errors:/root/.caddy/errors"
